"""create table

Revision ID: 416f288a669a
Revises: 0e12555d4c52
Create Date: 2023-06-22 22:47:50.684090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416f288a669a'
down_revision = '0e12555d4c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
